set shell := [ "bash", "-c" ]

default:
	@just time

build:
	llc-17 -O=3 -filetype=obj -o abort.o abort.ll
	llc-17 -O=3 -filetype=obj -o alloc.o alloc.ll
	llc-17 -O=3 -filetype=obj -o alloc_test.o alloc_test.ll
	llc-17 -O=3 -filetype=obj -o sys.o sys.ll
	llc-17 -O=3 -filetype=obj -o thread.o thread.ll

	ld -o alloc_test abort.o alloc.o sys.o thread.o alloc_test.o
	rm *.o

strace:
	@just build
	strace -x ./alloc_test >/dev/null

time:
	@just build
	time ./alloc_test
