set shell := [ "bash", "-c" ]

default:
	@just time

build:
	@just compile generic/abort.ll
	@just compile generic/alloc.ll
	@just compile linux-x86_64/sys.ll
	@just compile linux-x86_64/thread.ll
	@just compile test/alloc_test.ll

	@just link alloc_test abort alloc sys thread alloc_test

compile path:
	llc-17 -O=3 -filetype=obj -o obj/{{file_stem(path)}}.o {{path}}

link output +objs:
	#!/bin/bash -e
	obj_paths=`for obj in {{objs}}; do echo obj/$obj.o; done`
	cmd="ld.lld-17 -o bin/{{output}} $obj_paths"
	echo $cmd
	$cmd

test:
	@just build
	bin/alloc_test

clean:
	rm -f bin/* obj/*

strace:
	@just build
	strace -x bin/alloc_test >/dev/null

time:
	@just build
	time bin/alloc_test
